import { BadgeCategory, MilestoneType, MetricType } from '../database/schemas/badge.schema';

export const badgesSeedData = [

  {
    name: 'First Plate',
    description: 'First successful Saveful cook',
    imageUrl: '/badges/onboarding/first-plate.png',
    category: BadgeCategory.ONBOARDING,
    milestoneType: MilestoneType.FIRST_RECIPE_COOKED,
    milestoneThreshold: 1,
    metricType: MetricType.FIRST_EVENT,
    rarityScore: 10,
    iconColor: '#4CAF50',
    isActive: true,
  },

  {
    name: 'Second Helping',
    description: 'Returning to Saveful',
    imageUrl: '/badges/usage/second-helping.png',
    category: BadgeCategory.USAGE,
    milestoneType: MilestoneType.TOTAL_APP_SESSIONS_3,
    milestoneThreshold: 3,
    metricType: MetricType.APP_SESSIONS,
    rarityScore: 20,
    iconColor: '#2196F3',
    isActive: true,
  },
  {
    name: 'On a Roll',
    description: 'Saveful becoming a habit',
    imageUrl: '/badges/usage/on-a-roll.png',
    category: BadgeCategory.USAGE,
    milestoneType: MilestoneType.TOTAL_APP_SESSIONS_7,
    milestoneThreshold: 7,
    metricType: MetricType.APP_SESSIONS,
    rarityScore: 30,
    iconColor: '#2196F3',
    isActive: true,
  },
  {
    name: 'Saveful Local',
    description: 'Saveful part of routine',
    imageUrl: '/badges/usage/saveful-local.png',
    category: BadgeCategory.USAGE,
    milestoneType: MilestoneType.TOTAL_APP_SESSIONS_20,
    milestoneThreshold: 20,
    metricType: MetricType.APP_SESSIONS,
    rarityScore: 40,
    iconColor: '#2196F3',
    isActive: true,
  },
  {
    name: 'Saveful Super Cook',
    description: 'High engagement',
    imageUrl: '/badges/usage/saveful-super-cook.png',
    category: BadgeCategory.USAGE,
    milestoneType: MilestoneType.TOTAL_APP_SESSIONS_50,
    milestoneThreshold: 50,
    metricType: MetricType.APP_SESSIONS,
    rarityScore: 50,
    iconColor: '#2196F3',
    isActive: true,
  },

  {
    name: 'Cooking up a Storm',
    description: 'Cooking regularly',
    imageUrl: '/badges/cooking/cooking-up-a-storm.png',
    category: BadgeCategory.COOKING,
    milestoneType: MilestoneType.RECIPES_COOKED_5,
    milestoneThreshold: 5,
    metricType: MetricType.RECIPES_COOKED,
    rarityScore: 25,
    iconColor: '#FF9800',
    isActive: true,
  },
  {
    name: 'Kitchen Confident',
    description: 'Confident home cooking',
    imageUrl: '/badges/cooking/kitchen-confident.png',
    category: BadgeCategory.COOKING,
    milestoneType: MilestoneType.RECIPES_COOKED_10,
    milestoneThreshold: 10,
    metricType: MetricType.RECIPES_COOKED,
    rarityScore: 35,
    iconColor: '#FF9800',
    isActive: true,
  },
  {
    name: 'Dinner Hero',
    description: 'Cooking as a system',
    imageUrl: '/badges/cooking/dinner-hero.png',
    category: BadgeCategory.COOKING,
    milestoneType: MilestoneType.RECIPES_COOKED_25,
    milestoneThreshold: 25,
    metricType: MetricType.RECIPES_COOKED,
    rarityScore: 45,
    iconColor: '#FF9800',
    isActive: true,
  },
  {
    name: 'Leftover Legend',
    description: 'Elite home cooking',
    imageUrl: '/badges/cooking/leftover-legend.png',
    category: BadgeCategory.COOKING,
    milestoneType: MilestoneType.RECIPES_COOKED_50,
    milestoneThreshold: 50,
    metricType: MetricType.RECIPES_COOKED,
    rarityScore: 60,
    iconColor: '#FF9800',
    isActive: true,
  },

  {
    name: 'Cha-Ching!',
    description: 'First money milestone',
    imageUrl: '/badges/money/cha-ching.png',
    category: BadgeCategory.MONEY_SAVED,
    milestoneType: MilestoneType.MONEY_SAVED_25,
    milestoneThreshold: 25,
    metricType: MetricType.MONEY_SAVED_CUMULATIVE,
    rarityScore: 30,
    iconColor: '#4CAF50',
    isActive: true,
  },
  {
    name: 'Super Saver',
    description: 'Strong grocery savings',
    imageUrl: '/badges/money/super-saver.png',
    category: BadgeCategory.MONEY_SAVED,
    milestoneType: MilestoneType.MONEY_SAVED_50,
    milestoneThreshold: 50,
    metricType: MetricType.MONEY_SAVED_CUMULATIVE,
    rarityScore: 40,
    iconColor: '#4CAF50',
    isActive: true,
  },
  {
    name: 'Mega Saver',
    description: 'Serious savings',
    imageUrl: '/badges/money/mega-saver.png',
    category: BadgeCategory.MONEY_SAVED,
    milestoneType: MilestoneType.MONEY_SAVED_100,
    milestoneThreshold: 100,
    metricType: MetricType.MONEY_SAVED_CUMULATIVE,
    rarityScore: 55,
    iconColor: '#4CAF50',
    isActive: true,
  },
  {
    name: 'Household Hero',
    description: 'Big household impact',
    imageUrl: '/badges/money/household-hero.png',
    category: BadgeCategory.MONEY_SAVED,
    milestoneType: MilestoneType.MONEY_SAVED_250,
    milestoneThreshold: 250,
    metricType: MetricType.MONEY_SAVED_CUMULATIVE,
    rarityScore: 70,
    iconColor: '#4CAF50',
    isActive: true,
  },
  {
    name: 'Ultimate Saver',
    description: 'Top-tier savings',
    imageUrl: '/badges/money/ultimate-saver.png',
    category: BadgeCategory.MONEY_SAVED,
    milestoneType: MilestoneType.MONEY_SAVED_500,
    milestoneThreshold: 500,
    metricType: MetricType.MONEY_SAVED_CUMULATIVE,
    rarityScore: 90,
    iconColor: '#4CAF50',
    isActive: true,
  },

  {
    name: 'Food Saver',
    description: 'First food saved',
    imageUrl: '/badges/food/food-saver.png',
    category: BadgeCategory.FOOD_SAVED,
    milestoneType: MilestoneType.FIRST_FOOD_SAVED,
    milestoneThreshold: 1,
    metricType: MetricType.FIRST_EVENT,
    rarityScore: 15,
    iconColor: '#8BC34A',
    isActive: true,
  },
  {
    name: 'Smart Kitchen',
    description: 'Small wins add up',
    imageUrl: '/badges/food/smart-kitchen.png',
    category: BadgeCategory.FOOD_SAVED,
    milestoneType: MilestoneType.FOOD_SAVED_5KG,
    milestoneThreshold: 5,
    metricType: MetricType.FOOD_WEIGHT_SAVED,
    rarityScore: 35,
    iconColor: '#8BC34A',
    isActive: true,
  },
  {
    name: 'Food Forward',
    description: 'Consistent saving',
    imageUrl: '/badges/food/food-forward.png',
    category: BadgeCategory.FOOD_SAVED,
    milestoneType: MilestoneType.FOOD_SAVED_10KG,
    milestoneThreshold: 10,
    metricType: MetricType.FOOD_WEIGHT_SAVED,
    rarityScore: 50,
    iconColor: '#8BC34A',
    isActive: true,
  },
  {
    name: 'Family Food Saver',
    description: 'Household scale',
    imageUrl: '/badges/food/family-food-saver.png',
    category: BadgeCategory.FOOD_SAVED,
    milestoneType: MilestoneType.FOOD_SAVED_15KG,
    milestoneThreshold: 15,
    metricType: MetricType.FOOD_WEIGHT_SAVED,
    rarityScore: 65,
    iconColor: '#8BC34A',
    isActive: true,
  },
  {
    name: 'Food-Saving Star',
    description: 'Best-in-class',
    imageUrl: '/badges/food/food-saving-star.png',
    category: BadgeCategory.FOOD_SAVED,
    milestoneType: MilestoneType.FOOD_SAVED_20KG,
    milestoneThreshold: 20,
    metricType: MetricType.FOOD_WEIGHT_SAVED,
    rarityScore: 80,
    iconColor: '#8BC34A',
    isActive: true,
  },

  {
    name: 'List Legend (Rookie)',
    description: 'First list created',
    imageUrl: '/badges/planning/list-legend-rookie.png',
    category: BadgeCategory.PLANNING,
    milestoneType: MilestoneType.SHOPPING_LIST_1,
    milestoneThreshold: 1,
    metricType: MetricType.SHOPPING_LISTS_CREATED,
    rarityScore: 15,
    iconColor: '#9C27B0',
    isActive: true,
  },
  {
    name: 'List Legend',
    description: 'Regular planner',
    imageUrl: '/badges/planning/list-legend.png',
    category: BadgeCategory.PLANNING,
    milestoneType: MilestoneType.SHOPPING_LIST_5,
    milestoneThreshold: 5,
    metricType: MetricType.SHOPPING_LISTS_CREATED,
    rarityScore: 30,
    iconColor: '#9C27B0',
    isActive: true,
  },
  {
    name: 'List Boss',
    description: 'Planning pro',
    imageUrl: '/badges/planning/list-boss.png',
    category: BadgeCategory.PLANNING,
    milestoneType: MilestoneType.SHOPPING_LIST_10,
    milestoneThreshold: 10,
    metricType: MetricType.SHOPPING_LISTS_CREATED,
    rarityScore: 45,
    iconColor: '#9C27B0',
    isActive: true,
  },
  {
    name: 'Master Planner',
    description: 'Total control',
    imageUrl: '/badges/planning/master-planner.png',
    category: BadgeCategory.PLANNING,
    milestoneType: MilestoneType.SHOPPING_LIST_25,
    milestoneThreshold: 25,
    metricType: MetricType.SHOPPING_LISTS_CREATED,
    rarityScore: 60,
    iconColor: '#9C27B0',
    isActive: true,
  },

  {
    name: 'Weeknight Warrior',
    description: 'Weekday dinner wins',
    imageUrl: '/badges/bonus/weeknight-warrior.png',
    category: BadgeCategory.BONUS,
    milestoneType: MilestoneType.WEEKDAY_MEALS_5,
    milestoneThreshold: 5,
    metricType: MetricType.WEEKDAY_MEALS_COOKED,
    rarityScore: 35,
    iconColor: '#FF5722',
    isActive: true,
  },
];

export const sponsorBadgeExamples = [
  {
    name: 'Qantas Frequent Flyer',
    description: 'Earn Qantas Points with Saveful',
    imageUrl: '/badges/sponsors/qantas.png',
    category: BadgeCategory.SPONSOR,
    isSponsorBadge: true,
    sponsorName: 'Qantas',
    sponsorLogoUrl: '/logos/qantas-logo.png',
    sponsorCountries: ['AU', 'NZ'],
    sponsorValidFrom: new Date('2026-01-01'),
    sponsorValidUntil: new Date('2026-12-31'),
    sponsorMetadata: {
      campaignId: 'QANTAS_2026_Q1',
      redemptionCode: 'SAVEFUL2026',
      sponsorLink: 'https://qantas.com/saveful',
      termsAndConditions: 'Qantas Points earned based on food saved. T&Cs apply.',
    },
    rarityScore: 100,
    iconColor: '#E0301E',
    isActive: true,
  },
  {
    name: 'Woolworths Everyday Rewards',
    description: 'Save more with Woolworths',
    imageUrl: '/badges/sponsors/woolworths.png',
    category: BadgeCategory.SPONSOR,
    isSponsorBadge: true,
    sponsorName: 'Woolworths',
    sponsorLogoUrl: '/logos/woolworths-logo.png',
    sponsorCountries: ['AU'],
    sponsorValidFrom: new Date('2026-01-01'),
    sponsorValidUntil: new Date('2026-06-30'),
    sponsorMetadata: {
      campaignId: 'WOOLWORTHS_H1_2026',
      sponsorLink: 'https://woolworths.com.au/saveful',
      termsAndConditions: 'Earn bonus Everyday Rewards points. T&Cs apply.',
    },
    rarityScore: 100,
    iconColor: '#009D4E',
    isActive: true,
  },
  {
    name: 'Saveful India Champion',
    description: 'Special recognition for Indian users',
    imageUrl: '/badges/sponsors/india-special.png',
    category: BadgeCategory.SPONSOR,
    isSponsorBadge: true,
    sponsorName: 'Saveful India',
    sponsorLogoUrl: '/logos/saveful-india.png',
    sponsorCountries: ['IN'],
    sponsorMetadata: {
      campaignId: 'INDIA_LAUNCH_2026',
      termsAndConditions: 'Available to all active users in India.',
    },
    rarityScore: 75,
    iconColor: '#FF9933',
    isActive: true,
  },
];
